---
- name: Download and add GPG Key
  shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add K8S repository to /etc/apt/sources.list.d/kubernetes.list
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Update apt repository and install kubernetes and its dependencies
  apt:
    pkg:
      - kubectl
      - kubeadm
      - kubelet
      - apt-transport-https
      - ca-certificates
      - git
      - golang-go
      - containerd
    update_cache: true

- name: Mkdir /etc/containerd
  file:
    path: /etc/containerd
    state: directory

- name: Config containerd
  template:
    src: containerd.config.toml.j2
    dest: /etc/containerd/config.toml
  notify:
    - Restart containerd

- name: Config K8s modules
  template:
    src: k8s_modules.conf.j2
    dest: /etc/modules-load.d/k8s.conf
  notify:
  - Load overlay kernel module
  - Load br_netfilter kernel module

- name: Config network modules
  template:
    src: k8s_sysctl.conf.j2
    dest: /etc/sysctl.d/k8s.conf
  notify:
  - Reload system modules

- name: Turn off the swap
  shell: swapoff -a
